### PR TITLE
Add call to `apt-get upgrade`

### PR DESCRIPTION
**Pull request by adamnfish**
It looks like this is missing the call to `apt-get upgrade`.

### CODE REVIEW

**Comment by philwills** [comment]
We should base this off one of the standard AMIs, as I'm not happy basing this startup relying on the AWS ubuntu repos.

Having said that, this is definitely an improvement, so :+1:

**Comment by adamnfish** [comment]
@philwills yep, but you're already using the repos to install stuff so that would be a change to the way it works at the moment. If you're using base AMIs that means you are accepting the burden of being pro-active about keeping them up to date.

**Comment by philwills** [comment]
Agreed, hence the :+1:

**Comment by philwills** [comment]
cc @rtyley @DiegoVazquezNanini @gidsg who may have stacks where this would make sense to apply.

**Pull request merged**
